In [249]:
import pandas as pd
import numpy as np
import os

In [250]:
original_df = pd.read_csv("../data/sst-sentiment-train.csv")
original_df.shape

(7898, 3)

# IMDB 50k dataset
binary sentiment

In [216]:
!pwd

/Users/hamzaahmedsiddiqui/Documents/Jupyterlab/dnlp_summer2025/nlp_2025_NiceLovablePeople/data_extra

In [230]:
df = pd.read_csv('IMDB Dataset.csv')
df.shape

(50000, 2)

In [231]:
df.head(2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    review sentiment
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the...  positive
1   A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.  positive

In [232]:
df = df.reset_index()

In [233]:
df.columns = ['id', 'sentence', 'sentiment']
df['id'] = 'xxx-' + df['id'].astype(str) + '-xxx'  
df.tail(2)

                  id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sentence sentiment
49998  xxx-49998-xxx  I'm going to have to disagree with the previous comment and side with Maltin on this one. This is a second rate, excessively vicious Western that creaks and groans trying to put across its central theme of the Wild West being tamed and kicked aside by the steady march of time. It would like to be in the tradition of "Butch Cassidy and the Sundance Kid", but lacks that film's poignancy and charm. Andrew McLaglen's direction is limp, and the final 30 minutes or so are a real botch, with some incomprehensible strategy on the part of heroes Charlton Heston and Chris Mitchum. (Someone give me a holler if you can explain to me why they set that hillside on fire.) There was something callous about the whole treatment of the rape scene, and the woman's reaction afterwards certainly did not ring true. Coburn is plenty nasty as the half breed escaped convict out for revenge, but all of his fellow escapees are underdeveloped (they're like bowling pins to be knocked down one by one as the stor...  negative
49999  xxx-49999-xxx                                                                                                                                                                                                                                                                                                                                   No one expects the Star Trek movies to be high art, but the fans do expect a movie that is as good as some of the best episodes. Unfortunately, this movie had a muddled, implausible plot that just left me cringing - this is by far the worst of the nine (so far) movies. Even the chance to watch the well known characters interact in another movie can't save this movie - including the goofy scenes with Kirk, Spock and McCoy at Yosemite.<br /><br />I would say this movie is not worth a rental, and hardly worth watching, however for the True Fan who needs to see all the movies, renting this movie is about the only way you'll see it - even the cable channels avoid this movie.  negative

In [234]:
df = df.replace({'sentiment': {'positive': 4, 'negative': 0}})
df.sample(5)

/var/folders/q7/r62zxy213ms4wg9xz6cljcnm0000gn/T/ipykernel_27610/2588608186.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'sentiment': {'positive': 4, 'negative': 0}})

                  id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sentence  sentiment
16506  xxx-16506-xxx  By the time it opened, "Heaven's Gate" had become, to its detriment, more a cultural phenomenon than a motion picture. At a time when concern about excessive budgets and directorial arrogance were growing, it was a convenient target, as it was a far-over-budget work by the latest "auteur" to hit Hollywood, who had not yet established the track record that would have given him the benefit of the doubt among critics and the industry alike. As someone pointed out at the time, no one was going to jump on Warren Beatty's even-more costly and dark "Reds," because Beatty was "one of us," while Michael Cimino had not achieved that status.<br /><br />But "Heaven's Gate" was also affected by a cultural change taking place at that time, the political move rightwards and toward a more unquestioning patriotism and enshrinement of the myth of the West (and the Western). A few years earlier, Cimino's demythologizing of the frontier might have seemed timely, fresh, and a necessary corrective. But ...          4
6961    xxx-6961-xxx                                                                                                                                                                                                                                                                                                                   This is a very fine and poetic story. Beautiful scenery. Magnificent music score. I've been twice in Japan last year and the movie gave me this typical Japanese feeling. The movement of the camera is superb, as well as the actors. It goes deep into your feelings without becoming melodramatic. Japanese people are very sensitive and kind and it's all very well brought onto the screen here. The director is playing superb with light an colors and shows the audience that it is also possible to let them enjoy a movie with subtle and fine details. Once you've seen this movie you will want to see more from the same director. It's a real feel good movie and I can only recommend it to everybody.          4
9166    xxx-9166-xxx  This relatively obscure Hong Kong "minorpiece" is the perfect desert island movie for video age peeping toms (at least its first half is). Every set-up, every scene, every sequence is an excuse to look up a girl's skirt, stare down at her breasts, gaze at her bottom and leer at her tight crotch. What it's establishing is the lead character's perverted proclivities, of course(!)<br /><br />Genre stalwart Anthony Wong is a marginally perverted married man who is plagued by erotic daydreams and outrageous fantasies. All involve scantily clad, sexy Chinese ladies with nothing but sexual servitude on their minds.<br /><br />The plot is thickened by a homicidal subplot, voodoo doll skewering and a little rape and pillage.<br /><br />Some of the sex scenes are fairly hot and the gore is liberal, but the supernatural elements introduced into the second half feel half-baked and the plot developments are ludicrous.<br /><br />Clearly, producer of garish garbage Wong Jing was in a terrible hu...          0
31354  xxx-31354-xxx                                                                                                     I love Meatballs! Terrific characters and poignant situations make this one dearly loved. Bill Murray is hysterical and you gotta love that 4-mile trail race at the end! A total classic and one of my favorites now for about 20 years. It brings back fond memories of camp and deals nicely with the experience of being rejected by foolish peers and the empowerment brought one by being rescued by a sympathetic adult. Tons of great one-liners and quite an assortment of wacko counselors. This is the kind of movie where you repeat key phrases among friends for years afterward. Also nothing overtly crude and what a sweet late '70's soundtrack to bring on just the right amount of nostalgia. I can't say enough about Meatballs; it's a classic. Be forewarned! All the sequels are putrid stink bombs that simply bought the name rights for marketing. They have no connection to Ivan Reitman's masterpiece.          4
43390  xxx-43390-xxx  Like wearing a hair shirt. Positively, absolutely, without a shadow of a doubt one of the worst movies ever. Pure torture. Zero stars out of ten. One long, tedious, labored, pretentious, self-conscious, theatrical, and leadenly artsy scene after another. Intended to be dreamlike and impressionistic, the soul bared, it is, instead, morose mush. <br /><br />Half-naked, father and son grope and whisper to each other like lovers. "Homo-erotic" is the point, loud and clear. OK, so what? <br /><br />Repeated more than once by the son is the line, supposedly lifted from "Lives of the Saints," "A father's love crucifies. A loving son lets himself be crucified." The parallel to god and his son, Christ, is heavy-handed, irrelevant, and bombastic, like everything else here. <br /><br />Some reference points to the theme of Russian filiality: "Mother and Son" (1997); "The Return" (Andrei Zvyagvatsev, 2003); "Little Odessa" (James Gray,1994); Turgenev, "Fathers and Sons"; and, of course, Dostoy...          0

In [240]:
# df = df.sample(frac=0.2, random_state=11711).reset_index(drop=True)  # shuffle the dataframe
# df.shape

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Name: sentence, Length: 50000, dtype: bool

In [241]:
df = df[df.sentence.apply(lambda x: len(x.split())) <= 56].reset_index(drop=True)  # filter sentences with more than 56
df.shape

(1856, 3)

In [ ]:
# find odd sentences which may break bert
df.sentence.apply(lambda x: len(x.split())).describe()

count    1856.000000
mean       45.319504
std         8.612206
min         4.000000
25%        41.000000
50%        47.000000
75%        52.000000
max        56.000000
Name: sentence, dtype: float64

In [224]:
# df['length'] = df.sentence.apply(lambda x: len(x.split()))
# df = df[df.length <= 510]
# del df['length']

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1856 entries, 0 to 1855
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1856 non-null   object
 1   sentence   1856 non-null   object
 2   sentiment  1856 non-null   int64
dtypes: int64(1), object(2)
memory usage: 43.6+ KB

In [245]:
# append df to original_df
df = pd.concat([original_df, df], axis=0).reset_index(drop=True) 
df

                                        id                                                                                                                                                                                                                                                                                                                                                        sentence  sentiment
0     9b15458c-1525-445e-92f7-653b40b5075e                                                                                                                                                                                                                                                                   The drama is played out with such aching beauty and truth that it brings tears to your eyes .          4
1     053849bf-3e34-41e7-99ff-f25644a24db0                                                                                                            It 's hard to care about a film that proposes as epic tragedy the plight of a callow rich boy who is forced to choose between his beautiful , self-satisfied 22-year-old girlfriend and an equally beautiful , self-satisfied 18-year-old mistress .          1
2     5ddd2560-c16b-42ed-8e9f-38bf04ae422b                                                                                                                                                                                                                               The entire point of a shaggy dog story , of course , is that it goes nowhere , and this is classic nowheresville in every sense .          1
3     74065550-f1f3-4924-aaa3-f50548629bb0                                                                                                                                                                                                                                                                                                          The sort of movie that gives tastelessness a bad rap .          0
4     bc516e7c-ab1a-4f1f-bc12-861cef164db9                                                                                                                                                                                       Criminal conspiracies and true romances move so easily across racial and cultural lines in the film that it makes My Big Fat Greek Wedding look like an apartheid drama .          3
...                                    ...                                                                                                                                                                                                                                                                                                                                                             ...        ...
9749                         xxx-49789-xxx                                                                                                                 Great characters, great acting, great dialogue, incredible plot twists in plain language one of the best shows I've ever seen in my life. Do yourself a favor and watch this show, you won't regret it. This show re-writes the book on Sci-Fi!          4
9750                         xxx-49902-xxx  Greenaway seems to have a habit of trying deliberately to disgust his viewers. This film opens with incest--and purposeless, meaningless, casual incest at that. That's Greenaway's big problem. He prefers parlor tricks to shock over actually doing anything meaningful. Technical skill isn't enough. He's just a bit perverse for the sake of perversity.          0
9751                         xxx-49910-xxx                                                                                                        This is one of those movies that showcases a great actor's talent and also conveys a great story. It is one of Stewart's greatest movies. Barring a few historic errors it also does an excellent job of telling the story of the "Spirit of St. Louis".          4
9752                         xxx-49929-xxx                                                                                    This is John Waters best film to date. The characters are obvious and symbolic, just as in his other films. So there are no surprises or character changes. I enjoyed the film because of the wittiness and pace of the story. It was good story-telling with honest people.          4
9753                         xxx-49942-xxx                                                                                                                                                                                                       The movie is not that bad, Ringo Lam sucks. I hate when Van Damme has love in his movies, van Damme is good only when he doesn't have love in his movies.          0

[9754 rows x 3 columns]

In [246]:
df.to_csv('../data/sst-sentiment-train.csv', index=False)

In [247]:
df.sentence.apply(lambda x: len(x.split())).describe()

count    9754.000000
mean       24.212118
std        13.683074
min         2.000000
25%        14.000000
50%        21.000000
75%        32.000000
max        56.000000
Name: sentence, dtype: float64

In [248]:
df.sentiment.value_counts(1)

sentiment
4    0.231597
1    0.216116
3    0.210478
0    0.190691
2    0.151117
Name: proportion, dtype: float64